trigger:
  - main  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Optional: Run unit tests here if you have any
  # - script: pytest

  - script: |
      streamlit run app.py
    displayName: 'Run Streamlit App'
